openapi: 3.0.0
info:
  title: Nettruyen
  description: 'Crawl from Nettruyen'
  contact:
    name: GingTeam
    url: 'https://facebook.com/gingdev'
  version: '1.0'
paths:
  /detail:
    get:
      tags:
        - Detail
      description: 'Return the list of episodes, detail of the story'
      operationId: 96b0c8721c7cb8aacb4fa26c397d0875
      parameters:
        -
          name: url
          in: query
          description: URL
          required: true
          schema:
            type: string
          example: 'https://www.nettruyenin.com/truyen-tranh/vo-luyen-dinh-phong-176960'
      responses:
        '200':
          description: 'Return if successful'
          content:
            application/json:
              schema:
                type: array
                items:
                  properties: { title: { type: string }, description: { type: string }, chapters: { type: array, items: { properties: { name: { type: string }, url: { type: string } }, type: object } } }
                  type: object
        '404':
          description: 'Return if failed'
  /read:
    get:
      tags:
        - Read
      description: 'Returns the list of paths of the images'
      operationId: a3ed720c545d3789de3a3f99800f10c3
      parameters:
        -
          name: url
          in: query
          description: URL
          required: true
          schema:
            type: string
          example: 'https://www.nettruyenin.com/truyen-tranh/vo-luyen-dinh-phong/chap-2793/929207'
      responses:
        '200':
          description: 'Return if successful'
          content:
            application/json:
              schema:
                type: array
                items:
                  description: 'Link of image'
                  type: string
        '404':
          description: 'Return if failed'
tags:
  -
    name: Read
  -
    name: Detail
